spring:
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/demo}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    client-id: ${KEYCLOAK_CLIENT_ID:demo-client}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:change-me}
  uma:
    audience: ${UMA_AUDIENCE:${app.security.client-id}}

---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/demo}

